dataset_name: NCMAPSS
h5_path: ${paths.data_dir}/NCMAPSS/N-CMAPSS_DS03-012.h5
source_fc: 1
target_fc: 3
window_size: 50
stride: 1
downsample_factor: 10
phase_threshold: 0.5
median_filter_length: 51
batch_size: 256
shuffle_train: true
