defaults:
  - _self_
  - paths: default
  - logger: console
  - dataset: cmapss
  - model: lstm_dann
  - trainer: lstm_dann_trainer
  - optimizer: sgd_lstm_dann
  - loss: lstm_dann_loss
  - experiment: null

task_name: 'default_experiment'
seed: 42
trials: 1
pipeline: 'lstm_dann'

hydra:
  run:
    dir: outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}
  sweep:
    dir: multirun/${now:%Y-%m-%d}/${now:%H-%M-%S}
    subdir: ${hydra.job.num}
  job:
    chdir: false
